export class PurchaseOrderLines {
    wmsPOLineNumber: any;
    upcEANNumber: string;
    quantity: string;
    discount: string;
    // tax1: number;
    // tax2: number;
    // tax3: number;
    // tax4: number;
    // tax5: number;
    netAmount: number;
    taxAmount: number;
    grossAmount: number;
    unitPrice: number;
    units: string;
    productMasterInfo: object;
    remarks: string;
    eta: Date;
    productImage: string;
    currency: string;
    purchaseTaxes: any;
    orderUnitPrice: number;
    brandName: string;
    createdBy: any;
    createdDate: any;
    hsnCode: any;
    productDescription: any = null;
    storageInstruction: any = null;
    discountAmount: any = null;
    taxPercentage: any = null;
    inventoryUnit: any = null;
    shipmentOrderLineID: any = null;
    uomConversionAvailability: any = null;
    _id: any = null;

    constructor(createPOLines: any, productMasterInfo: any) {
        this.wmsPOLineNumber = createPOLines.wmsPOLineNumber;
        this.productMasterInfo = Object.assign({}, productMasterInfo);
        this.productDescription = createPOLines.productDescription;
        this.storageInstruction = createPOLines.storageInstruction;
        this.upcEANNumber = createPOLines.upcEANNumber || '';
        this.quantity = createPOLines.quantity;
        this.netAmount = createPOLines.netAmount;
        this.taxAmount = createPOLines.taxAmount;
        this.grossAmount = createPOLines.grossAmount;
        this.discount = createPOLines.discount;
        this.discountAmount = createPOLines.discountAmount;
        this.taxPercentage = createPOLines.taxPercentage;
        // this.tax1 = createPOLines.tax1;
        // this.tax2 = createPOLines.tax2;
        // this.tax3 = createPOLines.tax3;
        // this.tax4 = createPOLines.tax4;
        // this.tax5 = createPOLines.tax5;
        this.unitPrice = createPOLines.unitPrice;
        this.currency = createPOLines.currency;
        this.units = createPOLines.units;
        this.remarks = createPOLines.remarks;
        this.eta = createPOLines.eta ? new Date(createPOLines.eta) : createPOLines.eta;
        this.productImage = createPOLines.productImage;
        this.purchaseTaxes = createPOLines.purchaseTaxes;
        this.orderUnitPrice = createPOLines.orderUnitPrice;
        this.brandName = createPOLines.brandName;
        this.createdBy = createPOLines.createdBy;
        this.createdDate = createPOLines.createdDate;
        this.hsnCode = createPOLines.hsnCode;
        this.inventoryUnit = createPOLines.inventoryUnit;
        this.shipmentOrderLineID = createPOLines.shipmentOrderLineID;
        this.uomConversionAvailability = createPOLines.uomConversionAvailability;
        this._id = createPOLines._id;
    }
}